- hosts: "{{ hosts }}"

  tasks:

    - name: Get disk usage
      command: df -h
      register: disk_usage

    - name: Check disk space available
      shell: df -h / | awk 'NR==2 {print $5}'
      register: disk_usage

    # Send Teams message when disk space is over 80%
    - name: Send a notification to Teams Channel
      uri:
        url: "https://emblibrary.webhook.office.com/webhookb2/b73972b2-b20d-4a3e-81c5-ddd4684ac5d6@9f26c4d8-8e42-44aa-b660-81deb27aafa4/IncomingWebhook/188f776951e44235925ea0720d44f84b/01c95630-9c61-4117-95f5-92363d19bbe3"
        method: POST
        body_format: json
        body: '{"content": "Disk space on {{ inventory_hostname }} is above 80%!"}'
        headers:
          Content-Type: application/json
        status_code: 204
      when: disk_usage.stdout[:-1]|int > 80
