---
- name: Check disk usage and notify Microsoft Teams
  hosts: all
  become: yes
  tasks:
    - name: Get disk usage
      shell: df -h --output=pcent / | tail -1 | tr -d '%'
      register: disk_usage

    - name: Check if disk usage is over 80%
      when: disk_usage.stdout | int > 80
      set_fact:
        alert: true

    - name: Send notification to Microsoft Teams
      uri:
        url: "https://emblibrary.webhook.office.com/webhookb2/b73972b2-b20d-4a3e-81c5-ddd4684ac5d6@9f26c4d8-8e42-44aa-b660-81deb27aafa4/IncomingWebhook/0750ba8d0b2b45ac8efbffa845abc14b/01c95630-9c61-4117-95f5-92363d19bbe3"
        method: POST
        headers:
          Content-Type: application/json
        body: |
          {
            "text": "Alert: Disk usage on host {{ inventory_hostname }} is at {{ disk_usage.stdout }}%."
          }
        status_code: 200
      when: alert is defined and alert | bool
