---
- hosts: all
  become: yes
  serial: 1

  tasks:
    # Upgrade packages
    - name: upgrade apt packages
      become: true
      apt:
        upgrade: yes
        update_cache: yes

    # Check if reboot is required
    - name: check if system reboot is required
      become: true
      stat:
        path: /var/run/reboot-required
      register: reboot_required

    # Send Teams message when reboot is required
    - name: Send Teams message
      uri:
        url: "https://emblibrary.webhook.office.com/webhookb2/b73972b2-b20d-4a3e-81c5-ddd4684ac5d6@9f26c4d8-8e42-44aa-b660-81deb27aafa4/IncomingWebhook/188f776951e44235925ea0720d44f84b/01c95630-9c61-4117-95f5-92363d19bbe3"
        method: POST
        body_format: json
        body: '{"content": "Reboot required on {{ inventory_hostname }}"}'
        headers:
          Content-Type: application/json
        status_code: 204
      when: reboot_required.stat.exists

    # Rebooting the host
    - name: Rebooting the host
      ansible.builtin.reboot:
      when: reboot_required.stat.exists

    # Wait for SSH to come back
    - name: Wait for SSH to come back
      ansible.builtin.wait_for_connection:
        delay: 60
        timeout: 300
      when: reboot_required.stat.exists
